import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        'getting-started/installation',
        'getting-started/quick-start',
      ],
    },
    {
      type: 'category',
      label: 'Tutorial',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'tutorial',
        },
      ],
    },
    {
      type: 'category',
      label: 'Recommendations',
      collapsed: false,
      items: [
        'recommendations/project-structure',
      ],
    },
    {
      type: 'category',
      label: 'Core Concepts',
      collapsed: false,
      items: [
        'core-concepts/nodes',
        'core-concepts/reactive-state',
        {
          type: 'category',
          label: 'Validation',
          collapsed: true,
          items: [
            'validation/overview',
            'validation/built-in',
            'validation/async',
            'validation/custom',
          ],
        },
        {
          type: 'category',
          label: 'Behaviors',
          collapsed: true,
          items: [
            'behaviors/overview',
            'behaviors/computed',
            'behaviors/conditional',
            'behaviors/sync',
            'behaviors/watch',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Frameworks',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'React',
          collapsed: true,
          items: [
            'react/hooks',
            'react/components',
          ],
        },
      ],
    },
  ],
  apiSidebar: [
    {
      type: 'doc',
      id: 'api/index',
      label: 'API Reference',
    },
    {
      type: 'category',
      label: 'Classes',
      items: [{ type: 'autogenerated', dirName: 'api/classes' }],
    },
    {
      type: 'category',
      label: 'Enumerations',
      items: [{ type: 'autogenerated', dirName: 'api/enumerations' }],
    },
    {
      type: 'category',
      label: 'Functions',
      items: [{ type: 'autogenerated', dirName: 'api/functions' }],
    },
    {
      type: 'category',
      label: 'Interfaces',
      items: [{ type: 'autogenerated', dirName: 'api/interfaces' }],
    },
    {
      type: 'category',
      label: 'Type Aliases',
      items: [{ type: 'autogenerated', dirName: 'api/type-aliases' }],
    },
    {
      type: 'category',
      label: 'Variables',
      items: [{ type: 'autogenerated', dirName: 'api/variables' }],
    },
  ],
};

export default sidebars;
