import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        'getting-started/installation',
        'getting-started/quick-start',
      ],
    },
    {
      type: 'category',
      label: 'Core Concepts',
      collapsed: false,
      items: [
        'core-concepts/nodes',
        'core-concepts/reactive-state',
      ],
    },
    {
      type: 'category',
      label: 'Validation',
      collapsed: true,
      items: [
        'validation/overview',
        'validation/built-in',
        'validation/async',
        'validation/custom',
      ],
    },
    {
      type: 'category',
      label: 'Behaviors',
      collapsed: true,
      items: [
        'behaviors/overview',
        'behaviors/computed',
        'behaviors/conditional',
        'behaviors/sync',
        'behaviors/watch',
      ],
    },
    {
      type: 'category',
      label: 'React Integration',
      collapsed: true,
      items: [
        'react/hooks',
        'react/components',
      ],
    },
  ],
  apiSidebar: [
    {
      type: 'autogenerated',
      dirName: 'api',
    },
  ],
};

export default sidebars;
