/**
 * Курируемый список частых Tailwind-утилит для автодополнения поля `className` в инспекторе.
 *
 * Это НЕ полный набор Tailwind (v4 генерирует классы под запрос — их перечислить нельзя): здесь
 * популярные утилиты layout/flex/grid/spacing/sizing/typography/цвета/границы/эффекты плюс
 * семантические токены дизайн-системы проекта (bg-muted, text-foreground, border-border…). Поле
 * остаётся свободным вводом — подсказки лишь ускоряют набор, любой кастомный класс допустим.
 *
 * @module reformer-builder/lib/tailwind-classes
 */

/** Частые числовые шкалы spacing (padding/margin/gap). */
const SPACE = [
  '0',
  '0.5',
  '1',
  '1.5',
  '2',
  '2.5',
  '3',
  '4',
  '5',
  '6',
  '8',
  '10',
  '12',
  '16',
  '20',
  '24',
];
/** Радиусы. */
const RADII = ['none', 'sm', '', 'md', 'lg', 'xl', '2xl', '3xl', 'full'];
/** Семантические цветовые токены дизайн-системы (shadcn) — то, что реально в ходу в проекте. */
const SEMANTIC = [
  'background',
  'foreground',
  'card',
  'card-foreground',
  'popover',
  'popover-foreground',
  'primary',
  'primary-foreground',
  'secondary',
  'secondary-foreground',
  'muted',
  'muted-foreground',
  'accent',
  'accent-foreground',
  'destructive',
  'destructive-foreground',
  'border',
  'input',
  'ring',
  'sidebar',
];
/** Палитра tailwind (подмножество оттенков для кастомных цветов). */
const PALETTE = [
  'slate',
  'gray',
  'zinc',
  'red',
  'orange',
  'amber',
  'yellow',
  'green',
  'emerald',
  'blue',
  'indigo',
  'violet',
];
const SHADES = ['400', '500', '600', '700'];

const scale = (prefix: string) => SPACE.map((s) => `${prefix}-${s}`);

const RAW: string[] = [
  // ─ Display ─
  'block',
  'inline-block',
  'inline',
  'flex',
  'inline-flex',
  'grid',
  'inline-grid',
  'hidden',
  'contents',
  'table',
  // ─ Flexbox ─
  'flex-row',
  'flex-row-reverse',
  'flex-col',
  'flex-col-reverse',
  'flex-wrap',
  'flex-nowrap',
  'flex-1',
  'flex-auto',
  'flex-initial',
  'flex-none',
  'grow',
  'grow-0',
  'shrink',
  'shrink-0',
  // ─ Align / justify ─
  'items-start',
  'items-center',
  'items-end',
  'items-stretch',
  'items-baseline',
  'justify-start',
  'justify-center',
  'justify-end',
  'justify-between',
  'justify-around',
  'justify-evenly',
  'self-start',
  'self-center',
  'self-end',
  'self-stretch',
  'self-auto',
  'content-start',
  'content-center',
  'content-between',
  'place-items-center',
  'place-content-center',
  // ─ Grid ─
  'grid-cols-1',
  'grid-cols-2',
  'grid-cols-3',
  'grid-cols-4',
  'grid-cols-5',
  'grid-cols-6',
  'grid-cols-12',
  'col-span-1',
  'col-span-2',
  'col-span-3',
  'col-span-full',
  'row-span-1',
  'row-span-2',
  'grid-flow-row',
  'grid-flow-col',
  'auto-cols-fr',
  'auto-rows-fr',
  // ─ Gap ─
  ...scale('gap'),
  ...scale('gap-x'),
  ...scale('gap-y'),
  // ─ Padding ─
  ...scale('p'),
  ...scale('px'),
  ...scale('py'),
  ...scale('pt'),
  ...scale('pr'),
  ...scale('pb'),
  ...scale('pl'),
  // ─ Margin ─
  ...scale('m'),
  ...scale('mx'),
  ...scale('my'),
  ...scale('mt'),
  ...scale('mr'),
  ...scale('mb'),
  ...scale('ml'),
  'mx-auto',
  'my-auto',
  'ml-auto',
  'mr-auto',
  // ─ Space between ─
  ...scale('space-x'),
  ...scale('space-y'),
  // ─ Width ─
  'w-full',
  'w-auto',
  'w-screen',
  'w-fit',
  'w-min',
  'w-max',
  'w-px',
  'w-1/2',
  'w-1/3',
  'w-2/3',
  'w-1/4',
  'w-3/4',
  ...scale('w'),
  // ─ Height ─
  'h-full',
  'h-auto',
  'h-screen',
  'h-fit',
  'h-min',
  'h-max',
  'h-px',
  ...scale('h'),
  // ─ Min/Max sizing ─
  'min-w-0',
  'min-w-full',
  'min-h-0',
  'min-h-full',
  'min-h-screen',
  'max-w-none',
  'max-w-xs',
  'max-w-sm',
  'max-w-md',
  'max-w-lg',
  'max-w-xl',
  'max-w-2xl',
  'max-w-full',
  'max-w-screen-md',
  'max-h-full',
  'max-h-screen',
  'size-full',
  'size-4',
  'size-5',
  'size-6',
  'size-8',
  'size-10',
  // ─ Typography ─
  'text-xs',
  'text-sm',
  'text-base',
  'text-lg',
  'text-xl',
  'text-2xl',
  'text-3xl',
  'text-4xl',
  'font-normal',
  'font-medium',
  'font-semibold',
  'font-bold',
  'font-light',
  'font-mono',
  'italic',
  'uppercase',
  'lowercase',
  'capitalize',
  'normal-case',
  'truncate',
  'text-balance',
  'text-pretty',
  'text-left',
  'text-center',
  'text-right',
  'text-justify',
  'leading-none',
  'leading-tight',
  'leading-snug',
  'leading-normal',
  'leading-relaxed',
  'leading-loose',
  'tracking-tight',
  'tracking-normal',
  'tracking-wide',
  'tracking-wider',
  'underline',
  'line-through',
  'no-underline',
  'whitespace-normal',
  'whitespace-nowrap',
  'whitespace-pre',
  'tabular-nums',
  'antialiased',
  // ─ Borders / radius ─
  'border',
  'border-0',
  'border-2',
  'border-4',
  'border-t',
  'border-r',
  'border-b',
  'border-l',
  ...RADII.map((r) => (r ? `rounded-${r}` : 'rounded')),
  'rounded-t-md',
  'rounded-b-md',
  'rounded-l-md',
  'rounded-r-md',
  // ─ Effects ─
  'shadow-none',
  'shadow-sm',
  'shadow',
  'shadow-md',
  'shadow-lg',
  'shadow-xl',
  'shadow-2xl',
  'shadow-inner',
  'opacity-0',
  'opacity-50',
  'opacity-70',
  'opacity-90',
  'opacity-100',
  'ring',
  'ring-1',
  'ring-2',
  'backdrop-blur',
  // ─ Position ─
  'relative',
  'absolute',
  'fixed',
  'sticky',
  'static',
  'inset-0',
  'inset-x-0',
  'inset-y-0',
  'top-0',
  'right-0',
  'bottom-0',
  'left-0',
  'z-0',
  'z-10',
  'z-20',
  'z-30',
  'z-40',
  'z-50',
  // ─ Overflow ─
  'overflow-auto',
  'overflow-hidden',
  'overflow-scroll',
  'overflow-visible',
  'overflow-x-auto',
  'overflow-y-auto',
  'overflow-x-hidden',
  'overflow-y-hidden',
  // ─ Interactivity / misc ─
  'cursor-pointer',
  'cursor-default',
  'cursor-not-allowed',
  'select-none',
  'select-text',
  'pointer-events-none',
  'pointer-events-auto',
  'transition',
  'transition-all',
  'transition-colors',
  'duration-150',
  'duration-200',
  'duration-300',
  'ease-in-out',
  // ─ Semantic color tokens (bg/text/border) ─
  ...SEMANTIC.map((c) => `bg-${c}`),
  ...SEMANTIC.map((c) => `text-${c}`),
  'text-white',
  'text-black',
  'border-border',
  'border-input',
  'border-ring',
  'border-destructive',
  'border-transparent',
  // ─ Palette color subset (custom colors) ─
  ...PALETTE.flatMap((c) => SHADES.map((s) => `bg-${c}-${s}`)),
  ...PALETTE.flatMap((c) => SHADES.map((s) => `text-${c}-${s}`)),
];

/** Уникальный список классов-подсказок (порядок — курируемый, по категориям). */
export const TAILWIND_CLASSES: string[] = Array.from(new Set(RAW));
