import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: true,
      items: ['getting-started/installation', 'getting-started/quick-start'],
    },
    {
      type: 'category',
      label: 'Tutorial',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'tutorial',
        },
      ],
    },
    {
      type: 'category',
      label: 'Core Concepts',
      collapsed: true,
      items: [
        'core-concepts/nodes',
        'core-concepts/reactive-state',
        {
          type: 'category',
          label: 'Schemas',
          collapsed: true,
          items: [
            'core-concepts/schemas/overview',
            'core-concepts/schemas/form-schema',
            'core-concepts/schemas/validation-schema',
            'core-concepts/schemas/behavior-schema',
            'core-concepts/schemas/composition',
          ],
        },
        {
          type: 'category',
          label: 'Validation',
          collapsed: true,
          items: [
            'validation/overview',
            'validation/built-in',
            'validation/async',
            'validation/custom',
            'validation/validation-strategies',
            'validation/error-handling',
          ],
        },
        {
          type: 'category',
          label: 'Behaviors',
          collapsed: true,
          items: [
            'behaviors/overview',
            'behaviors/computed',
            'behaviors/conditional',
            'behaviors/sync',
            'behaviors/watch',
            'behaviors/custom',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Patterns',
      collapsed: true,
      items: ['patterns/project-structure', 'patterns/openapi-generation'],
    },
    {
      type: 'category',
      label: 'Frameworks',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'React',
          collapsed: true,
          items: ['react/hooks', 'react/custom-fields'],
        },
      ],
    },
  ],
  apiSidebar: [
    {
      type: 'doc',
      id: 'api/index',
      label: 'API Reference',
    },
    {
      type: 'category',
      label: 'Classes',
      items: [{ type: 'autogenerated', dirName: 'api/classes' }],
    },
    {
      type: 'category',
      label: 'Enumerations',
      items: [{ type: 'autogenerated', dirName: 'api/enumerations' }],
    },
    {
      type: 'category',
      label: 'Functions',
      items: [{ type: 'autogenerated', dirName: 'api/functions' }],
    },
    {
      type: 'category',
      label: 'Interfaces',
      items: [{ type: 'autogenerated', dirName: 'api/interfaces' }],
    },
    {
      type: 'category',
      label: 'Type Aliases',
      items: [{ type: 'autogenerated', dirName: 'api/type-aliases' }],
    },
    {
      type: 'category',
      label: 'Variables',
      items: [{ type: 'autogenerated', dirName: 'api/variables' }],
    },
  ],
};

export default sidebars;
