import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // ── Core: базовый пакет + вся сквозная база (гайд, концепции, валидация,
  // behaviors, React, паттерны) + Core API Reference (typedoc). ──────────────
  coreSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Начало работы',
      collapsed: false,
      items: ['getting-started/installation', 'getting-started/quick-start'],
    },
    {
      type: 'category',
      label: 'Основные концепции',
      collapsed: true,
      items: [
        'core-concepts/reactive-state',
        'core-concepts/model',
        'core-concepts/nodes',
        {
          type: 'category',
          label: 'Схемы',
          collapsed: true,
          items: [
            'core-concepts/schemas/overview',
            'core-concepts/schemas/form-schema',
            'core-concepts/schemas/validation-schema',
            'core-concepts/schemas/behavior-schema',
            'core-concepts/schemas/composition',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Валидация',
      collapsed: true,
      items: [
        'validation/overview',
        'validation/built-in',
        'validation/custom',
        'validation/async',
        'validation/validation-strategies',
        'validation/error-handling',
      ],
    },
    {
      type: 'category',
      label: 'Behaviors',
      collapsed: true,
      items: [
        'behaviors/overview',
        'behaviors/computed',
        'behaviors/conditional',
        'behaviors/sync',
        'behaviors/watch',
        'behaviors/custom',
      ],
    },
    {
      type: 'category',
      label: 'Интеграция с React',
      collapsed: true,
      items: ['react/hooks', 'react/custom-fields'],
    },
    {
      type: 'category',
      label: 'Рекомендованные паттерны',
      collapsed: true,
      items: [
        'patterns/project-structure',
        'patterns/arrays',
        'patterns/submit-and-reset',
        'patterns/async-preload',
        'patterns/openapi-generation',
      ],
    },
    {
      type: 'category',
      label: 'Core API Reference',
      collapsed: true,
      link: { type: 'doc', id: 'api/index' },
      items: [
        {
          type: 'category',
          label: 'Classes',
          items: [{ type: 'autogenerated', dirName: 'api/classes' }],
        },
        {
          type: 'category',
          label: 'Enumerations',
          items: [{ type: 'autogenerated', dirName: 'api/enumerations' }],
        },
        {
          type: 'category',
          label: 'Functions',
          items: [{ type: 'autogenerated', dirName: 'api/functions' }],
        },
        {
          type: 'category',
          label: 'Interfaces',
          items: [{ type: 'autogenerated', dirName: 'api/interfaces' }],
        },
        {
          type: 'category',
          label: 'Type Aliases',
          items: [{ type: 'autogenerated', dirName: 'api/type-aliases' }],
        },
      ],
    },
  ],

  // ── CDK: headless-компоненты ───────────────────────────────────────────────
  cdkSidebar: [
    'cdk/overview',
    'cdk/async-boundary',
    'cdk/form-array',
    'cdk/form-wizard',
    'cdk/form-field',
  ],

  // ── UI-Kit: стилизованные компоненты, сгруппированные по семействам ─────────
  uiKitSidebar: [
    'ui-kit/overview',
    // v7-миграция: категории компонентов наполняются оркестратором между волнами
    // (см. docs/plans/jazzy-sniffing-kahan.md).
    {
      type: 'category',
      label: 'Текстовые поля',
      collapsed: false,
      items: [
        'ui-kit/input',
        'ui-kit/textarea',
        'ui-kit/input-otp',
        'ui-kit/input-group',
        'ui-kit/input-mask',
        'ui-kit/input-password',
      ],
    },
    {
      type: 'category',
      label: 'Выбор',
      collapsed: false,
      items: [
        'ui-kit/select',
        'ui-kit/native-select',
        'ui-kit/checkbox',
        'ui-kit/radio-group',
        'ui-kit/switch',
        'ui-kit/toggle',
        'ui-kit/toggle-group',
        'ui-kit/slider',
        'ui-kit/calendar',
        'ui-kit/combobox',
        'ui-kit/date-picker',
      ],
    },
    {
      type: 'category',
      label: 'Действия',
      collapsed: false,
      items: ['ui-kit/button'],
    },
    {
      type: 'category',
      label: 'Отображение',
      collapsed: false,
      items: [
        'ui-kit/badge',
        'ui-kit/card',
        'ui-kit/alert',
        'ui-kit/skeleton',
        'ui-kit/avatar',
        'ui-kit/progress',
        'ui-kit/carousel',
        'ui-kit/chart',
        'ui-kit/typography',
        'ui-kit/example-card',
      ],
    },
    {
      type: 'category',
      label: 'Оверлеи',
      collapsed: false,
      items: [
        'ui-kit/dialog',
        'ui-kit/alert-dialog',
        'ui-kit/sheet',
        'ui-kit/popover',
        'ui-kit/hover-card',
        'ui-kit/tooltip',
        'ui-kit/dropdown-menu',
        'ui-kit/context-menu',
        'ui-kit/drawer',
        'ui-kit/command',
        'ui-kit/sonner',
      ],
    },
    {
      type: 'category',
      label: 'Навигация и раскрытие',
      collapsed: false,
      items: [
        'ui-kit/accordion',
        'ui-kit/tabs',
        'ui-kit/menubar',
        'ui-kit/navigation-menu',
        'ui-kit/breadcrumb',
        'ui-kit/pagination',
      ],
    },
    {
      type: 'category',
      label: 'Служебные и layout',
      collapsed: false,
      items: [
        'ui-kit/aspect-ratio',
        'ui-kit/scroll-area',
        'ui-kit/collapsible',
        'ui-kit/button-group',
        'ui-kit/item',
        'ui-kit/empty',
        'ui-kit/spinner',
        'ui-kit/kbd',
        'ui-kit/resizable',
        'ui-kit/direction',
        'ui-kit/async-boundary',
        'ui-kit/box',
        'ui-kit/section',
      ],
    },
    {
      type: 'category',
      label: 'AI-примитивы',
      collapsed: false,
      items: [
        'ui-kit/bubble',
        'ui-kit/attachment',
        'ui-kit/marker',
        'ui-kit/message',
        'ui-kit/message-scroller',
      ],
    },
    {
      type: 'category',
      label: 'Составные',
      collapsed: false,
      items: ['ui-kit/table', 'ui-kit/sidebar', 'ui-kit/form-array', 'ui-kit/form-navigation'],
    },
  ],

  // ── Renderer: оба пакета (renderer-react + renderer-json) ──────────────────
  rendererSidebar: [
    { type: 'doc', id: 'packages/renderer-react', label: '@reformer/renderer-react' },
    { type: 'doc', id: 'packages/renderer-json', label: '@reformer/renderer-json' },
  ],

  // ── MCP: сервер для AI-ассистентов ─────────────────────────────────────────
  mcpSidebar: ['mcp/overview', 'mcp/quick-start', 'mcp/tools', 'mcp/prompts', 'mcp/examples'],
};

export default sidebars;
