import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // ── Core: базовый пакет + вся сквозная база (гайд, концепции, валидация,
  // behaviors, React, паттерны) + Core API Reference (typedoc). ──────────────
  coreSidebar: [
    { type: 'doc', id: 'packages/core', label: '@reformer/core' },
    'intro',
    {
      type: 'category',
      label: 'Начало работы',
      collapsed: false,
      items: ['getting-started/installation', 'getting-started/quick-start'],
    },
    {
      type: 'category',
      label: 'Основные концепции',
      collapsed: true,
      items: [
        'core-concepts/reactive-state',
        'core-concepts/model',
        'core-concepts/nodes',
        {
          type: 'category',
          label: 'Схемы',
          collapsed: true,
          items: [
            'core-concepts/schemas/overview',
            'core-concepts/schemas/form-schema',
            'core-concepts/schemas/validation-schema',
            'core-concepts/schemas/behavior-schema',
            'core-concepts/schemas/composition',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Валидация',
      collapsed: true,
      items: [
        'validation/overview',
        'validation/built-in',
        'validation/custom',
        'validation/async',
        'validation/validation-strategies',
        'validation/error-handling',
      ],
    },
    {
      type: 'category',
      label: 'Behaviors',
      collapsed: true,
      items: [
        'behaviors/overview',
        'behaviors/computed',
        'behaviors/conditional',
        'behaviors/sync',
        'behaviors/watch',
        'behaviors/custom',
      ],
    },
    {
      type: 'category',
      label: 'Интеграция с React',
      collapsed: true,
      items: ['react/hooks', 'react/custom-fields'],
    },
    {
      type: 'category',
      label: 'Рекомендованные паттерны',
      collapsed: true,
      items: [
        'patterns/project-structure',
        'patterns/arrays',
        'patterns/submit-and-reset',
        'patterns/async-preload',
        'patterns/openapi-generation',
      ],
    },
    {
      type: 'category',
      label: 'Core API Reference',
      collapsed: true,
      link: { type: 'doc', id: 'api/index' },
      items: [
        {
          type: 'category',
          label: 'Classes',
          items: [{ type: 'autogenerated', dirName: 'api/classes' }],
        },
        {
          type: 'category',
          label: 'Enumerations',
          items: [{ type: 'autogenerated', dirName: 'api/enumerations' }],
        },
        {
          type: 'category',
          label: 'Functions',
          items: [{ type: 'autogenerated', dirName: 'api/functions' }],
        },
        {
          type: 'category',
          label: 'Interfaces',
          items: [{ type: 'autogenerated', dirName: 'api/interfaces' }],
        },
        {
          type: 'category',
          label: 'Type Aliases',
          items: [{ type: 'autogenerated', dirName: 'api/type-aliases' }],
        },
      ],
    },
  ],

  // ── CDK: headless-компоненты ───────────────────────────────────────────────
  cdkSidebar: [
    { type: 'doc', id: 'packages/cdk', label: '@reformer/cdk' },
    'cdk/form-array',
    'cdk/form-wizard',
    'cdk/form-field',
  ],

  // ── UI-Kit: стилизованные компоненты, сгруппированные по семействам ─────────
  uiKitSidebar: [
    { type: 'doc', id: 'packages/ui-kit', label: '@reformer/ui-kit' },
    'ui-kit/overview',
    {
      type: 'category',
      label: 'Текстовые поля',
      collapsed: false,
      items: ['ui-kit/input', 'ui-kit/input-password', 'ui-kit/input-mask', 'ui-kit/textarea'],
    },
    {
      type: 'category',
      label: 'Выбор',
      collapsed: false,
      items: ['ui-kit/select', 'ui-kit/checkbox', 'ui-kit/radio-group'],
    },
    {
      type: 'category',
      label: 'Действия и раскладка',
      collapsed: false,
      items: ['ui-kit/button'],
    },
    {
      type: 'category',
      label: 'Составные',
      collapsed: false,
      items: ['ui-kit/form-array', 'ui-kit/form-navigation'],
    },
  ],

  // ── Renderer: оба пакета (renderer-react + renderer-json) ──────────────────
  rendererSidebar: [
    { type: 'doc', id: 'packages/renderer-react', label: '@reformer/renderer-react' },
    { type: 'doc', id: 'packages/renderer-json', label: '@reformer/renderer-json' },
  ],

  // ── MCP: сервер для AI-ассистентов ─────────────────────────────────────────
  mcpSidebar: [
    { type: 'doc', id: 'packages/mcp', label: '@reformer/mcp' },
    'mcp/overview',
    'mcp/quick-start',
    'mcp/tools',
    'mcp/prompts',
    'mcp/examples',
  ],
};

export default sidebars;
